name: Private Action

on:
  workflow_dispatch:
    inputs:
      username:
        required: true
      image:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo "User: ${{ github.event.inputs.username }}"
          echo "Image: ${{ github.event.inputs.image }}"

