name: Private Action

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      image:
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "User: ${{ inputs.username }}"
          echo "Image: ${{ inputs.image }}"

